#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one
# Install nginx web server
	# Install nginx on your web-01
	# server
	# Nginx should be listening on port 80
	# When querying Nginx at its root / with a GET request. . . .the string Hello World!

# update & install
sapt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
