#!/usr/bin/env bash
# configure ubunu server to instal nginx

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
echo  "Hello World!" | sudo tee /var/www/html/index.html 

# test nginx config
sudo nginx -t
sudo service nginx restart
sudo service nginx reload 
