#!/usr/bin/env bash
# configure ubunu server to instal nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo  "Hello World!" | sudo tee /var/www/html/index.html 
# sudo service nginx start

# test nginx config
sudo nginx -t
sudo service nginx reload 
