#!/usr/bin/env bash
# installs nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/default
sudo sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/custom_404.html

sudo service nginx restart
