#!/usr/bin/env bash
# Not found page 404

# Updating and installations
sudo apt-get update
sudo apt-get install nginx -y

# an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirection (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/engedasew-haile permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing config
sudo nginx -t

# restart nginx 
sudo service nginx restart
